 const cars = [
   {
      id: 1,
      name: "Scorpio",
      image: "/assets/cars4.avif",
       images:["/assets/cars4.avif",
            "/assets/Scorpio.jpg",
            "/assets/Scorpioinside1.jpg",
            "/assets/Scorpioinside2.jpg",
            "/assets/Scorpioinside3.jpg",
        ],
      price: 250,
      distance: 196.3,
      rating:"⭐4.5",
      seats:"6",
    },
    {
      id: 2,
      name: "Mahindra thar",
       image: "/assets/Mahindra thar.jpg",
    images:["/assets/Mahindra thar.jpg",
      "/assets/Mahindra tharinside1.jpg",
      "/assets/Mahindra tharinside2.jpg",
      "/assets/Mahindra tharinside3.jpg",
      "/assets/Mahindra tharinside4.jpg",
    ],
      price: 180,
      distance: 245.4,
      rating:"⭐5.0", 
      seats:"4",

    },
     {
      id: 3,
      name: "Mahindra Scorpio N",
      image: "/assets/Mahindra Scorpio N.avif",
      images:["/assets/Mahindra Scorpio N.avif",
      "/assets/Mahindra Scorpio Ninside1.jpg",
      "/assets/Mahindra Scorpio Ninside2.jpg",
      "/assets/Mahindra Scorpio N3.jpg",
      "/assets/Mahindra Scorpio Ninside4.jpg",
    ],
      price: 200,
      distance: 103.1,
      rating:"⭐5.0",
      seats:"5"
     },
     {
      id: 4,
      name: "maruti suzuki alto k10",
        images:["/assets/cars8.jpg",
            "/assets/Maruti Suzuki Alto k19inside1.webp",
             "/assets/Maruti Suzuki Alto k19inside2.webp",
             "/assets/Maruti Suzuki Alto k19inside3.webp",
             "/assets/Maruti Suzuki Alto k19inside4.webp",
        ],
      image: "/assets/cars8.jpg",
      price: 100,
      distance: 143.1,
      rating:"⭐4.0",
      seats:"5",
    },
  {
      id: 5,
      name: "maruti suzuki Tour H3",
      image: "/assets/cars9.webp",
      images:[
            "/assets/cars9.webp",
            "/assets/maruti suzuki Tour H3inside.jpg",
            "/assets/maruti suzuki Tour H3inside1.jpg",
            "/assets/maruti suzuki Tour H3inside2.jpg",
            "/assets/maruti suzuki Tour H3inside3.jpg",
        ],
      price: 100,
      distance: 103.1,
      rating:"⭐5.0",
      seats:"5",
    },
    {
      id:6,
      name:"Tata tiger",
      image :"/assets/cars10.avif",
       images:["/assets/cars10.avif",
            "/assets/Tata punch inside1.jpg",
            "/assets/Tata tigerinside2.jpg",
            "/assets/Tata tigerinside3.jpg",
            "/assets/Tata tigerinside4.jpg",
        ],
      price:80,
      distance:"200",
      rating:"⭐5.0",
      seats:"5",
    },
  
    {
      id: 7,
      name: "Maruti Jimny",
      image: "/assets/Maruti Jimny.avif",
      images: ["/assets/Maruti Jimny.avif",
      "/assets/Maruti Jimnyinsde1.jpg",
      "/assets/Maruti Jimnyinside2.jpg",
      "/assets/Maruti Jimnyinsde3.jpg",
      "/assets/Maruti Jimnyinsde4.jpg",
    ],
      price: 100,
      distance: 103.1,
      rating:"⭐5.0",
      seats:"4",
    },
    {
      id:8,
      name:"Marutie vitara",
      image :"/assets/Marutie vitara.avif",
      images: ["/assets/Marutie vitara.avif",
      "/assets/Marutie vitarainsde1.jpg",
      "/assets/Marutie vitarainsde2.jpg",
      "/assets/Marutie vitarainsde3.jpg",
      "/assets/Maruti Suzuki Alto k19inside4.webp",
    ],
      price:90,
      distance:"200",
      rating:"⭐5.0",
      seats:"5",
    }
  ];
  export default cars