const cars = [
  {
    id: 1,
    name: "Mahindra Scorpio N",
    image: "/assets/Mahindra Scorpio N.avif",
    images:["/assets/Mahindra Scorpio N.avif",
      "/assets/Mahindra Scorpio Ninside1.jpg",
      "/assets/Mahindra Scorpio Ninside2.jpg",
      "/assets/Mahindra Scorpio N3.jpg",
      "/assets/Mahindra Scorpio Ninside4.jpg",
    ],
    price: 200,
    distance: 103.1,
    rating: "⭐5.0",
    seats: "5",
  },
  {
    id: 2,
    name: "Mahindra thar",
    image: "/assets/Mahindra thar.jpg",
    images:["/assets/Mahindra thar.jpg",
      "/assets/Mahindra tharinside1.jpg",
      "/assets/Mahindra tharinside2.jpg",
      "/assets/Mahindra tharinside3.jpg",
      "/assets/Mahindra tharinside4.jpg",
    ],
    price: 180,
    distance: 245.4,
    rating: "⭐5.0",
    seats: "4",

  },
  {
    id: 3,
    name: "Mahindra Thar ROXX",
    image: "/assets/Mahindra Thar ROXX.avif",
    images:["/assets/Mahindra Thar ROXX.avif",
      "/assets/Mahindra Thar ROXXinside1.jpg",
      "/assets/Mahindra Thar ROXXinside2.jpg",
      "/assets/Mahindra Thar ROXXinside2.jpg",
      "/assets/Mahindra Thar ROXXinsde4.jpg",
    ],
    price: 216,
    distance: 196.3,
    rating: "⭐4.5",
    seats: "5",
  },
  {
    id: 4,
    name: "Toyota Land Cruiser",
    image: "/assets/Toyota Land Cruiser.avif",
    images: ["assets/Toyota Land Cruiser.avi",
      "/assets/Toyota Land Cruiserinside2.jpg",
      "/assets/Toyota Land Cruiserinside3.jpg",
      "/assets/Toyota Land Cruiserinsde1.jpg",
    ],
    price: 250,
    distance: 96.3,
    rating: "⭐4.5",
    seats: "5",
  },
  {
    id: 5,
    name: "Toyota Fortuner",
    image: "/assets/Toyota Fortuner1.avif",
    images: ["/assets/Toyota Fortuner1.avif",
      "/assets/Toyota Fortunerinside1.jpg",
      "/assets/Toyota Fortunerinside2.jpg",
      "/assets/Toyota Fortunerinsde3.jpg",
      "/assets/Toyota Fortunerinsde4.jpg",

    ],
    price: 90,
    distance: 103.1,
    rating: "⭐5.0",
    seats: "5",
  },
  {
    id: 6,
    name: "Mini Cooper",
    image: "/assets/Mini Cooper.jpg",
    images: ["/assets/Mini Cooper.jpg",
      "/assets/Mini Cooperinsde1.jpg",
      "/assets/Mini Cooperinsde2.jpg",
      "/assets/Mini Cooperinsde3.jpg",
      "/assets/Mini Cooperinside4.jpg",
    ],

    price: 110,
    distance: 143.1,
    rating: "⭐4.0",
    seats: "4",
  },

  {
    id: 7,
    name: "Maruti Jimny",
    image: "/assets/Maruti Jimny.avif",
    images: ["/assets/Maruti Jimny.avif",
      "/assets/Maruti Jimnyinsde1.jpg",
      "/assets/Maruti Jimnyinside2.jpg",
      "/assets/Maruti Jimnyinsde3.jpg",
      "/assets/Maruti Jimnyinsde4.jpg",
    ],
    price: 100,
    distance: 103.1,
    rating: "⭐5.0",
    seats: "4",
  },
  {
    id: 8,
    name: "Marutie vitara",
    image: "/assets/Marutie vitara.avif",
    images: ["/assets/Marutie vitara.avif",
      "/assets/Marutie vitarainsde1.jpg",
      "/assets/Marutie vitarainsde2.jpg",
      "/assets/Marutie vitarainsde3.jpg",
      "/assets/Maruti Suzuki Alto k19inside4.webp",
    ],
    price: 80,
    distance: "200",
    rating: "⭐5.0",
    seats: "5",
  },
  {
    id: 8,
    name: "BMW X7",
    image: "/assets/BMW X7.avif",
    images: ["/assets/BMW X7.avif",
      "/assets/BMW X7inside1.jpg",
      "/assets/BMW X7inside2.jpg",
      "/assets/BMW X7insde3.jpg",
      "/assets/BMW X7insde4.jpg",
    ],
    price: 90,
    distance: "200",
    rating: "⭐5.0",
    seats: "5",
  }
];
export default cars