const cars = [
    {
      id: 1,
      name: "Mahindra Scorpio N",
      image: "/assets/Mahindra Scorpio N.avif",
      images:["/assets/Mahindra Scorpio N.avif",
      "/assets/Mahindra Scorpio Ninside1.jpg",
      "/assets/Mahindra Scorpio Ninside2.jpg",
      "/assets/Mahindra Scorpio N3.jpg",
      "/assets/Mahindra Scorpio Ninside4.jpg",
    ],
      price: 200,
      distance: 103.1,
      rating:"⭐5.0",
      seats:"5",
    },
   {
      id: 2,
      name: "Mini Cooper",
      image: "/assets/Mini Cooper.jpg",
      images: ["/assets/Mini Cooper.jpg",
      "/assets/Mini Cooperinsde1.jpg",
      "/assets/Mini Cooperinsde2.jpg",
      "/assets/Mini Cooperinsde3.jpg",
      "/assets/Mini Cooperinside4.jpg",
    ],
      price: 250,
      distance: 196.3,
      rating:"⭐4.5",
      seats:"2",
    },
    {
      id: 3,
      name: "Mahindra Thar ROXX",
      image: "/assets/Mahindra Thar ROXX.avif",
       images:["/assets/Mahindra Thar ROXX.avif",
      "/assets/Mahindra Thar ROXXinside1.jpg",
      "/assets/Mahindra Thar ROXXinside2.jpg",
      "/assets/Mahindra Thar ROXXinside2.jpg",
      "/assets/Mahindra Thar ROXXinsde4.jpg",
    ],
      price: 216,
      distance: 196.3,
      rating:"⭐4.5",
      seats:"5",
    },
     {
      id: 4,
      name: "Toyota Land Cruiser",
      image: "/assets/Toyota Land Cruiser.avif",
      images: ["/assets/Toyota Land Cruiser.avi",
      "/assets/Toyota Land Cruiserinside2.jpg",
      "/assets/Toyota Land Cruiserinside3.jpg",
      "/assets/Toyota Land Cruiserinsde1.jpg",
    ],
      price: 250,
      distance: 96.3,
      rating:"⭐4.5",
      seats:"5",
    },
    {
      id: 5,
      name: "Toyota Fortuner",
      image: "/assets/Toyota Fortuner1.avif",
       images: ["/assets/Toyota Fortuner1.avif",
      "/assets/Toyota Fortunerinside1.jpg",
      "/assets/Toyota Fortunerinside2.jpg",
      "/assets/Toyota Fortunerinsde3.jpg",
      "/assets/Toyota Fortunerinsde4.jpg",
    ],
      price: 90,
      distance: 103.1,
      rating:"⭐5.0",
      seats:"5",
    },
    {
      id: 6,
      name: "MG Cyberster ",
      image: "/assets/MG Cyberster.webp",
      images:["/assets/MG Cyberster.webp",
        "/assets/MG Cybersterinsde1.jpg",
        "/assets/MG Cybersterinsde3.jpg",
        "/assets/MG Cyberster insde2.jpg",
        "/assets/MG Cybersterinside4.jpg",
    ],
      price: 340,
      distance: 103.1,
      rating:"⭐5.0",
      seats:"2",
    },
    {
      id:7,
      name:"Marutie vitara",
      image :"/assets/Marutie vitara.avif",
      images: ["/assets/Marutie vitara.avif",
      "/assets/Marutie vitarainsde1.jpg",
      "/assets/Marutie vitarainsde2.jpg",
      "/assets/Marutie vitarainsde3.jpg",
      "/assets/Maruti Suzuki Alto k19inside4.webp",
    ],
      price:80,
      distance:"200",
      rating:"⭐5.0",
      seats:"5",
    },
     {
      id: 8,
      name:"Mahindra Thar",
     image: "/assets/Mahindra thar.jpg",
    images:["/assets/Mahindra thar.jpg",
      "/assets/Mahindra tharinside1.jpg",
      "/assets/Mahindra tharinside2.jpg",
      "/assets/Mahindra tharinside3.jpg",
      "/assets/Mahindra tharinside4.jpg",
    ],
      price: 216,
      distance: 196.3,
      rating:"⭐4.5",
      seats:"5",
    },
     {
      id: 9,
      name: "Land  Rover Defender ",
      image: "/assets/Land Rover Defender.jpg",
      images:["/assets/Land Rover Defender.jpg",
        "/assets/Land Rover Defenderinsdie1.jpg",
        "/assets/Land Rover Defenderinsdie2.jpg",
        "/assets/Land Rover Defenderinsdie3.jpg",
        "/assets/Land Rover Defenderinsdie4.jpg",
    ],
      price: 300,
      distance: 143.1,
      rating:"⭐4.0",
      seats:"5",
    },
  ];
  export default cars