const cars = [
    {
        id: 1,
        name: "Tata Punch 2025",
        image: "/assets/cars1.jpg",
        images:
            [
                "/assets/Tata punch inside5.jpg",
                "/assets/Tata punch inside1.jpg",
                "/assets/Tata punch inside2.jpg",
                "/assets/Tata punch inside3.jpg",
                "/assets/Tata punch inside4.jpg",
            ],
        price: 100,
        distance: 103.1,
        rating: "⭐5.0",
        seats: "5",
    },
    {
        id: 2,
        name: "Maruti Suzuki Celerio 2019",
        image: "/assets/cars6.webp",
        images: ["/assets/cars6.webp",
            "/assets/Maruti Suzuki Celerio4.webp",
            "/assets/Maruti Suzuki Celerioinside2.jpg",
            "/assets/Maruti Suzuki Celerioinside3.jpg",

        ],
        price: 180,
        distance: 245.4,
        rating: "⭐5.0",
        seats: "4",

    },
    {
        id: 3,
        name: "Hyundai Verna 2023",
        image: "/assets/car3.jpg",
        images:["/assets/car3.jpg",
            "/assets/hyundai Vernainside1.jpg",
            "/assets/hyundai Vernainside2.jpg",
            "/assets/hyundai Vernainside3.jpg",
            "/assets/hyundai Vernainside4.jpg",
        ],
        price: 216,
        distance: 196.3,
        rating: "⭐4.5",
        seats: "5",
    },
    {
        id: 4,
        name: "Scorpio",
        image: "/assets/cars4.avif",
        images:["/assets/cars4.avif",
            "/assets/Scorpio.jpg",
            "/assets/Scorpioinside1.jpg",
            "/assets/Scorpioinside2.jpg",
            "/assets/Scorpioinside3.jpg",
        ],
        price: 250,
        distance: 196.3,
        rating: "⭐4.5",
        seats: "6",
    },
    {
        id: 5,
        name: "Fit 2025",
        image: "/assets/car7.webp",
        images:["/assets/car7.webp",
            "/assets/Fitinside1.jpg",
            "/assets/Fitinside2.jpg",
            "/assets/Fitinside3.jpg",
        ],
        price: 100,
        distance: 103.1,
        rating: "⭐5.0",
        seats: "5",
    },
    {
        id: 6,
        name: "maruti suzuki alto k10",
        image: "/assets/cars8.jpg",
        images:["/assets/cars8.jpg",
            "/assets/Maruti Suzuki Alto k19inside1.webp",
             "/assets/Maruti Suzuki Alto k19inside2.webp",
             "/assets/Maruti Suzuki Alto k19inside3.webp",
             "/assets/Maruti Suzuki Alto k19inside4.webp",
        ],
        price: 100,
        distance: 143.1,
        rating: "⭐4.0",
        seats: "5",
    },

    {
        id: 7,
        name: "maruti suzuki Tour H3",
        image: "/assets/cars9.webp",
        images:[
            "/assets/cars9.webp",
            "/assets/maruti suzuki Tour H3inside.jpg",
            "/assets/maruti suzuki Tour H3inside1.jpg",
            "/assets/maruti suzuki Tour H3inside2.jpg",
            "/assets/maruti suzuki Tour H3inside3.jpg",
        ],
        price: 100,
        distance: 103.1,
        rating: "⭐5.0",
        seats: "5",
    },
    {
        id: 8,
        name: "Tata tiger",
        image: "/assets/cars10.avif",
        images:["/assets/cars10.avif",
            "/assets/Tata punch inside1.jpg",
            "/assets/Tata tigerinside2.jpg",
            "/assets/Tata tigerinside3.jpg",
            "/assets/Tata tigerinside4.jpg",
        ],
        price: 80,
        distance: "200",
        rating: "⭐5.0",
        seats: "5",
    },
     {
    id: 9,
    name: "Mahindra Scorpio N",
    image: "/assets/Mahindra Scorpio N.avif",
    images:["/assets/Mahindra Scorpio N.avif",
      "/assets/Mahindra Scorpio Ninside1.jpg",
      "/assets/Mahindra Scorpio Ninside2.jpg",
      "/assets/Mahindra Scorpio N3.jpg",
      "/assets/Mahindra Scorpio Ninside4.jpg",
    ],
    price: 200,
    distance: 103.1,
    rating: "⭐5.0",
    seats: "5",
  },
  {
    id: 10,
    name: "Mahindra thar",
    image: "/assets/Mahindra thar.jpg",
    images:["/assets/Mahindra thar.jpg",
      "/assets/Mahindra tharinside1.jpg",
      "/assets/Mahindra tharinside2.jpg",
      "/assets/Mahindra tharinside3.jpg",
      "/assets/Mahindra tharinside4.jpg",
    ],
    price: 180,
    distance: 245.4,
    rating: "⭐5.0",
    seats: "4",

  },
  {
    id: 11,
    name: "Mahindra Thar ROXX",
    image: "/assets/Mahindra Thar ROXX.avif",
    images:["/assets/Mahindra Thar ROXX.avif",
      "/assets/Mahindra Thar ROXXinside1.jpg",
      "/assets/Mahindra Thar ROXXinside2.jpg",
      "/assets/Mahindra Thar ROXXinside2.jpg",
      "/assets/Mahindra Thar ROXXinsde4.jpg",
    ],
    price: 216,
    distance: 196.3,
    rating: "⭐4.5",
    seats: "5",
  },
  {
    id: 12,
    name: "Toyota Land Cruiser",
    image: "/assets/Toyota Land Cruiser.avif",
    images: ["assets/Toyota Land Cruiser.avi",
      "/assets/Toyota Land Cruiserinside2.jpg",
      "/assets/Toyota Land Cruiserinside3.jpg",
      "/assets/Toyota Land Cruiserinsde1.jpg",
    ],
    price: 250,
    distance: 96.3,
    rating: "⭐4.5",
    seats: "5",
  },
  {
    id: 13,
    name: "Toyota Fortuner",
    image: "/assets/Toyota Fortuner1.avif",
    images: ["/assets/Toyota Fortuner1.avif",
      "/assets/Toyota Fortunerinside1.jpg",
      "/assets/Toyota Fortunerinside2.jpg",
      "/assets/Toyota Fortunerinsde3.jpg",
      "/assets/Toyota Fortunerinsde4.jpg",

    ],
    price: 90,
    distance: 103.1,
    rating: "⭐5.0",
    seats: "5",
  },
  {
    id: 14,
    name: "Mini Cooper",
    image: "/assets/Mini Cooper.jpg",
    images: ["/assets/Mini Cooper.jpg",
      "/assets/Mini Cooperinsde1.jpg",
      "/assets/Mini Cooperinsde2.jpg",
      "/assets/Mini Cooperinsde3.jpg",
      "/assets/Mini Cooperinside4.jpg",
    ],

    price: 110,
    distance: 143.1,
    rating: "⭐4.0",
    seats: "4",
  },

  {
    id: 15,
    name: "Maruti Jimny",
    image: "/assets/Maruti Jimny.avif",
    images: ["/assets/Maruti Jimny.avif",
      "/assets/Maruti Jimnyinsde1.jpg",
      "/assets/Maruti Jimnyinside2.jpg",
      "/assets/Maruti Jimnyinsde3.jpg",
      "/assets/Maruti Jimnyinsde4.jpg",
    ],
    price: 100,
    distance: 103.1,
    rating: "⭐5.0",
    seats: "4",
  },
  {
    id: 16,
    name: "Marutie vitara",
    image: "/assets/Marutie vitara.avif",
    images: ["/assets/Marutie vitara.avif",
      "/assets/Marutie vitarainsde1.jpg",
      "/assets/Marutie vitarainsde2.jpg",
      "/assets/Marutie vitarainsde3.jpg",
      "/assets/Maruti Suzuki Alto k19inside4.webp",
    ],
    price: 80,
    distance: "200",
    rating: "⭐5.0",
    seats: "5",
  },
  {
    id: 17,
    name: "BMW X7",
    image: "/assets/BMW X7.avif",
    images: ["/assets/BMW X7.avif",
      "/assets/BMW X7inside1.jpg",
      "/assets/BMW X7inside2.jpg",
      "/assets/BMW X7insde3.jpg",
      "/assets/BMW X7insde4.jpg",
    ],
    price: 90,
    distance: "200",
    rating: "⭐5.0",
    seats: "5",
},
        {
      id: 18,
      name: "MG Comet Ev",
      image: "/assets/Mg comet Ev.avif",
      images:["/assets/Mg comet Ev.avif",
        "/assets/MG Comet Evinside1.jpg",
        "/assets/MG Comet Evinside2.jpg",
        "/assets/MG Comet Evinside3.jpg",
        "/assets/MG Comet Evinside4.jpg",
        ],
      price: 100,
      distance: 103.1,
      rating:"⭐5.0",
      seats:"5",
    },
    {
      id: 19,
      name: "MG Cyberster ",
      image: "/assets/Mg Cyberster.avif",
      images:["/assets/Mg Cyberster.avif",
        "/assets/MG Cybersterniside1.jpg",
        "/assets/MG Cybersterinside2.jpg",
        "/assets/MG Cybersterinsde1.jpg",
      "/assets/MG Cybersterinside4.jpg",
      ],
      price: 180,
      distance: 245.4,
      rating:"⭐5.0", 
      seats:"4",

    },
    {
      id: 20,
      name: "MG M9",
      image: "/assets/Mg M9.avif",
      images:["/assets/Mg M9.avif",
        "/assets/MG M9insde3.jpg",
        "/assets/MG M9inside1.jpg",
        "/assets/MG M9inside2.jpg",
      ],
      price: 216,
      distance: 196.3,
      rating:"⭐4.5",
      seats:"5",
    },
     {
      id: 21,
      name: "MG Windsor EV.",
      image: "/assets/Mg windsor Ev.avif",
      images:["/assets/Mg windsor Ev.avif",
        "/assets/MG Windsor EVinsde3.jpg",
        "/assets/MG Windsor EVinside4.jpg",
        "/assets/MG Windsor EVinside2.jpg",
        "/assets/MG Windsor EVinside1.jpg",
      ],
      price: 250,
      distance: 196.3,
      rating:"⭐4.5",
      seats:"6",
    },
    {
      id: 22,
      name: "MG ZS EV.",
      image: "/assets/mg ZS EV.avif",
      images:["/assets/mg ZS EV.avif",
        "/assets/MG ZS EVinside2.jpg",
        "/assets/MG ZS EVinside3.jpg",
        "/assets/MG ZS EVinside4.jpg",
        "/assets/MG ZS EVinside1.jpg",
      ],
      price: 100,
      distance: 103.1,
      rating:"⭐5.0",
      seats:"5",
    },
      
    {
      id: 23,
      name: "Range Rover",
      image: "/assets/Range Rover.jpg",
      images:["/assets/Range Rover.jpg",
        "/assets/Range Roverinside1.jpg",  
        "/assets/Range Roverinside2.jpg",
        "/assets/Range Roverinside3.jpg",
        "/assets/Range Roverinside4.jpg",
      ],
      price: 280,
      distance: 245.4,
      rating:"⭐5.0", 
      seats:"4",

    },
    {
      id: 24,
      name: "Porsche 911",
      image: "/assets/Porsche 911.jpg",
      images:["/assets/Porsche 911.jpg",
        "/assets/Porsche 911inside1.jpg",  
        "/assets/Porsche 911inside2.jpg",
        "/assets/Porsche 911inside3.jpg",
        "/assets/Porsche 911inside4.jpg",
      ],
      price: 216,
      distance: 196.3,
      rating:"⭐4.5",
      seats:"2",
    },
    
    
    {
      id: 25,
      name: "Land  Rover Defender ",
      image: "/assets/Land Rover Defender.jpg",
      images:["/assets/Land Rover Defender.jpg",
        "/assets/Land Rover Defenderinsdie1.jpg",
        "/assets/Land Rover Defenderinsdie2.jpg",
        "/assets/Land Rover Defenderinsdie3.jpg",
        "/assets/Land Rover Defenderinsdie4.jpg",
    ],
      price: 300,
      distance: 143.1,
      rating:"⭐4.0",
      seats:"5",
    },
  
    {
      id: 26,
      name: "Land Cruiser",
      image: "/assets/land Cruiser.jpg",
      images:["/assets/land Cruiser.jpg",
        "/assets/land Cruiserinside1.jpg",
        "/assets/land Cruiserinside2.jpg",
        "/assets/land Cruiserinside3.jpg",  
        "/assets/land Cruiserinside4.jpg",
      ],
      price: 300,
      distance: 103.1,
      rating:"⭐5.0",
      seats:"5",
    },
    {
      id:27,
      name:"Lamborghini Urus ",
      image :"/assets/Lamborghini Urus.jpg",
      images:["/assets/Lamborghini Urus.jpg",
        "/assets/Lamborghini Urusinside1.jpg",
        "/assets/amborghini Urusinside2.jpg",
        "/assets/Lamborghini Urusinside3.jpg",
        "/assets/Lamborghini Urusinside4.jpg",
      ],      

      price:540,
      distance:"200",
      rating:"⭐5.0",
      seats:"4",
    },
    
]
export default cars