const Electric = [
    {
      id: 1,
      name: "MG Comet Ev",
      image: "/assets/Mg comet Ev.avif",
      images:["/assets/Mg comet Ev.avif",
        "/assets/MG Comet Evinside1.jpg",
        "/assets/MG Comet Evinside2.jpg",
        "/assets/MG Comet Evinside3.jpg",
        "/assets/MG Comet Evinside4.jpg",
        ],
      price: 100,
      distance: 103.1,
      rating:"⭐5.0",
      seats:"5",
    },
    {
      id: 2,
      name: "MG Cyberster ",
      image: "/assets/Mg Cyberster.avif",
      images:["/assets/Mg Cyberster.avif",
        "/assets/MG Cybersterniside1.jpg",
        "/assets/MG Cybersterinside2.jpg",
        "/assets/MG Cybersterinsde1.jpg",
      "/assets/MG Cybersterinside4.jpg",
      ],
      price: 180,
      distance: 245.4,
      rating:"⭐5.0", 
      seats:"4",

    },
    {
      id: 3,
      name: "MG M9",
      image: "/assets/Mg M9.avif",
      images:["/assets/Mg M9.avif",
        "/assets/MG M9insde3.jpg",
        "/assets/MG M9inside1.jpg",
        "/assets/MG M9inside2.jpg",
      ],
      price: 216,
      distance: 196.3,
      rating:"⭐4.5",
      seats:"5",
    },
     {
      id: 4,
      name: "MG Windsor EV.",
      image: "/assets/Mg windsor Ev.avif",
      images:["/assets/Mg windsor Ev.avif",
        "/assets/MG Windsor EVinsde3.jpg",
        "/assets/MG Windsor EVinside4.jpg",
        "/assets/MG Windsor EVinside2.jpg",
        "/assets/MG Windsor EVinside1.jpg",
      ],
      price: 250,
      distance: 196.3,
      rating:"⭐4.5",
      seats:"6",
    },
    {
      id: 5,
      name: "MG ZS EV.",
      image: "/assets/mg ZS EV.avif",
      images:["/assets/mg ZS EV.avif",
        "/assets/MG ZS EVinside2.jpg",
        "/assets/MG ZS EVinside3.jpg",
        "/assets/MG ZS EVinside4.jpg",
        "/assets/MG ZS EVinside1.jpg",
      ],
      price: 100,
      distance: 103.1,
      rating:"⭐5.0",
      seats:"5",
    },
    
  ];
  export default Electric 