const cars = [
    {
        id: 1,
        name: "Tata Punch 2025",
        image: "/assets/cars1.jpg",
        images:
            [
                "/assets/Tata punch inside5.jpg",
                "/assets/Tata punch inside1.jpg",
                "/assets/Tata punch inside2.jpg",
                "/assets/Tata punch inside3.jpg",
                "/assets/Tata punch inside4.jpg",
            ],
        price: 100,
        distance: 103.1,
        rating: "⭐5.0",
        seats: "5",
    },
    {
        id: 2,
        name: "Maruti Suzuki Celerio 2019",
        image: "/assets/cars6.webp",
        images: ["/assets/cars6.webp",
            "/assets/Maruti Suzuki Celerio4.webp",
            "/assets/Maruti Suzuki Celerioinside2.jpg",
            "/assets/Maruti Suzuki Celerioinside3.jpg",

        ],
        price: 180,
        distance: 245.4,
        rating: "⭐5.0",
        seats: "4",

    },
    {
        id: 3,
        name: "Hyundai Verna 2023",
        image: "/assets/car3.jpg",
        images:["/assets/car3.jpg",
            "/assets/hyundai Vernainside1.jpg",
            "/assets/hyundai Vernainside2.jpg",
            "/assets/hyundai Vernainside3.jpg",
            "/assets/hyundai Vernainside4.jpg",
        ],
        price: 216,
        distance: 196.3,
        rating: "⭐4.5",
        seats: "5",
    },
    {
        id: 4,
        name: "Scorpio",
        image: "/assets/cars4.avif",
        images:["/assets/cars4.avif",
            "/assets/Scorpio.jpg",
            "/assets/Scorpioinside1.jpg",
            "/assets/Scorpioinside2.jpg",
            "/assets/Scorpioinside3.jpg",
        ],
        price: 250,
        distance: 196.3,
        rating: "⭐4.5",
        seats: "6",
    },
    {
        id: 5,
        name: "Fit 2025",
        image: "/assets/car7.webp",
        images:["/assets/car7.webp",
            "/assets/Fitinside1.jpg",
            "/assets/Fitinside2.jpg",
            "/assets/Fitinside3.jpg",
        ],
        price: 100,
        distance: 103.1,
        rating: "⭐5.0",
        seats: "5",
    },
    {
        id: 6,
        name: "maruti suzuki alto k10",
        image: "/assets/cars8.jpg",
        images:["/assets/cars8.jpg",
            "/assets/Maruti Suzuki Alto k19inside1.webp",
             "/assets/Maruti Suzuki Alto k19inside2.webp",
             "/assets/Maruti Suzuki Alto k19inside3.webp",
             "/assets/Maruti Suzuki Alto k19inside4.webp",
        ],
        price: 100,
        distance: 143.1,
        rating: "⭐4.0",
        seats: "5",
    },

    {
        id: 7,
        name: "maruti suzuki Tour H3",
        image: "/assets/cars9.webp",
        images:[
            "/assets/cars9.webp",
            "/assets/maruti suzuki Tour H3inside.jpg",
            "/assets/maruti suzuki Tour H3inside1.jpg",
            "/assets/maruti suzuki Tour H3inside2.jpg",
            "/assets/maruti suzuki Tour H3inside3.jpg",
        ],
        price: 100,
        distance: 103.1,
        rating: "⭐5.0",
        seats: "5",
    },
    {
        id: 8,
        name: "Tata tiger",
        image: "/assets/cars10.avif",
        images:["/assets/cars10.avif",
            "/assets/Tata punch inside1.jpg",
            "/assets/Tata tigerinside2.jpg",
            "/assets/Tata tigerinside3.jpg",
            "/assets/Tata tigerinside4.jpg",
        ],
        price: 80,
        distance: "200",
        rating: "⭐5.0",
        seats: "5",
    }
];
export default cars