
 const cars = [
    {
      id: 1,
      name: "Toyota Fortuner ",
      image: "/assets/Toyota Fortuner1.avif",
       images: ["/assets/Toyota Fortuner1.avif",
      "/assets/Toyota Fortunerinside1.jpg",
      "/assets/Toyota Fortunerinside2.jpg",
      "/assets/Toyota Fortunerinsde3.jpg",
      "/assets/Toyota Fortunerinsde4.jpg",

    ],
      price: 100,
      distance: 103.1,
      rating:"⭐5.0",
      seats:"5",
    },
    {
      id: 2,
      name: "Range Rover",
      image: "/assets/Range Rover.jpg",
      images:["/assets/Range Rover.jpg",
        "/assets/Range Roverinside1.jpg",  
        "/assets/Range Roverinside2.jpg",
        "/assets/Range Roverinside3.jpg",
        "/assets/Range Roverinside4.jpg",
      ],
      price: 280,
      distance: 245.4,
      rating:"⭐5.0", 
      seats:"4",

    },
    {
      id: 3,
      name: "Porsche 911",
      image: "/assets/Porsche 911.jpg",
      images:["/assets/Porsche 911.jpg",
        "/assets/Porsche 911inside1.jpg",  
        "/assets/Porsche 911inside2.jpg",
        "/assets/Porsche 911inside3.jpg",
        "/assets/Porsche 911inside4.jpg",
      ],
      price: 216,
      distance: 196.3,
      rating:"⭐4.5",
      seats:"2",
    },
     {
      id: 4,
      name: "Mini Cooper",
      image: "/assets/Mini Cooper.jpg",
      images: ["/assets/Mini Cooper.jpg",
      "/assets/Mini Cooperinsde1.jpg",
      "/assets/Mini Cooperinsde2.jpg",
      "/assets/Mini Cooperinsde3.jpg",
      "/assets/Mini Cooperinside4.jpg",
    ],
      price: 250,
      distance: 196.3,
      rating:"⭐4.5",
      seats:"2",
    },
    {
      id: 5,
      name: "MG Cyberster ",
      image: "/assets/MG Cyberster.webp",
       images:["/assets/MG Cyberster.webp",
        "/assets/MG Cybersterinsde1.jpg",
        "/assets/MG Cybersterinsde3.jpg",
        "/assets/MG Cyberster insde2.jpg",
        "/assets/MG Cybersterinside4.jpg",
    ],
      price: 340,
      distance: 103.1,
      rating:"⭐5.0",
      seats:"2",
    },
    {
      id: 6,
      name: "Land  Rover Defender ",
      image: "/assets/Land Rover Defender.jpg",
      images:["/assets/Land Rover Defender.jpg",
        "/assets/Land Rover Defenderinsdie1.jpg",
        "/assets/Land Rover Defenderinsdie2.jpg",
        "/assets/Land Rover Defenderinsdie3.jpg",
        "/assets/Land Rover Defenderinsdie4.jpg",
    ],
      price: 300,
      distance: 143.1,
      rating:"⭐4.0",
      seats:"5",
    },
  
    {
      id: 7,
      name: "Land Cruiser",
      image: "/assets/land Cruiser.jpg",
      images:["/assets/land Cruiser.jpg",
        "/assets/land Cruiserinside1.jpg",
        "/assets/land Cruiserinside2.jpg",
        "/assets/land Cruiserinside3.jpg",  
        "/assets/land Cruiserinside4.jpg",
      ],
      price: 300,
      distance: 103.1,
      rating:"⭐5.0",
      seats:"5",
    },
    {
      id:8,
      name:"Lamborghini Urus ",
      image :"/assets/Lamborghini Urus.jpg",
      images:["/assets/Lamborghini Urus.jpg",
        "/assets/Lamborghini Urusinside1.jpg",
        "/assets/amborghini Urusinside2.jpg",
        "/assets/Lamborghini Urusinside3.jpg",
        "/assets/Lamborghini Urusinside4.jpg",
      ],      

      price:540,
      distance:"200",
      rating:"⭐5.0",
      seats:"4",
    },
    {
      id:9,
      name:"MG M9  ",
      image :"/assets/Mg M9.avif",
      images:["/assets/Mg M9.avif",
        "/assets/MG M9insde3.jpg",
        "/assets/MG M9inside1.jpg",
        "/assets/MG M9inside2.jpg",
      ],
      price:800,
      distance:"200",
      rating:"⭐5.0",
      seats:"5",
    }
  ];
  export default cars